version: "3.7"

services:
  host:
    build:
      dockerfile: ./infra/Dockerfile
      context: ./
      target: DEVELOPMENT
    volumes:
      - ./host:/app/host
    hostname: host
    working_dir: /app/host
    command: yarn start
    env_file: ./.env
    ports:
      - "8080:8080"

  counter:
    build:
      dockerfile: ./infra/Dockerfile
      context: ./
      target: DEVELOPMENT
    volumes:
      - ./counter:/app/counter
    hostname: counter
    working_dir: /app/counter
    command: yarn start
    env_file: ./.env
    ports:
      - "8081:8081"
