version: "3.7"

services:
  host:
    build:
      dockerfile: ../infra/Dockerfile
      context: ./host
      target: DEVELOPMENT
    volumes:
      - ./host:/app
    hostname: host
    command: yarn start
    env_file: ./.env
    depends_on:
      - counter
    ports:
      - "8080:8080"

  counter:
    build:
      dockerfile: ../infra/Dockerfile
      context: ./counter
      target: DEVELOPMENT
    volumes:
      - ./counter:/app
    hostname: counter
    command: yarn start
    env_file: ./.env
    ports:
      - "8081:8081"

  production:
    build:
      dockerfile: ./infra/Dockerfile
      context: ./
      target: PRODUCTION
    hostname: production
    env_file: ./.env
    ports:
      - "80:8080"
